# Generated by Django 3.2.16 on 2022-12-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_timetracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='final_time',
            field=models.IntegerField(default=0),
        ),
    ]
