# Generated by Django 3.2.16 on 2022-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20221211_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracker',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
