# Generated by Django 3.2.16 on 2022-12-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_timetracker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
