# Generated by Django 3.2.16 on 2022-12-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_timetracker_counting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='counting',
            field=models.BooleanField(default=False),
        ),
    ]
