# Generated by Django 3.2.16 on 2022-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_timetracker_counting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='final_time',
            field=models.DateTimeField(),
        ),
    ]
